### ISSUE TITLE
Plugin doesn't load in Nexus 2.10.0-02

### ISSUE THREAD

**Issue by akurdyukov** [PatrickRoumanoff/nexus-crowd-plugin#22]
Hi!

I tried to install plugin into Nexus 2.10.0-02. Log has
```
2014-10-30 15:55:44,337+0400 WARN  [jetty-main-1] *SYSTEM org.sonatype.nexus.NxApplication - Plugin manager request "ACTIVATE" on plugin "com.roumanoff.nexus:nexus-crowd-plugin:2.7.0" FAILED!
The following plugins were processed:
... com.roumanoff.nexus:nexus-crowd-plugin:2.7.0 :: action=ACTIVATE result=BROKEN
       Reason: Problem installing: reference:file:/opt/sonatype-work/nexus/plugin-repository/nexus-crowd-plugin-2.7.0/
```

How can I debug actual problem?

**Comment by philbeiler** [comment]
I'm using the 2.9.0 version of the plugin with Nexus 2.11.0-02. The plugin loads fine, but it is not working.  I have crowd working with Jenkins and other tools, and I have confirmed the user id information in the crowd console. 

Does the plugin work with this version?  

The log is very non informative.. I basically get a
Found JSESSIONID cooking value [********], followed by
UnknownSessionException -- There is no session with id [ ********]

Thanks for any assistance!

**Comment by flopma** [comment]
I'm running plugin v2.9.0 against Nexus 2.11.1-01 with any glitch.

**Comment by flopma** [comment]
Closing. Running plugin v2.9.0 against Nexus 2.11.2-04.
