### ISSUE TITLE
Not able to login with Jira User Server users

### ISSUE THREAD

**Issue by kalganesan** [PatrickRoumanoff/nexus-crowd-plugin#23]
hi team,

I am trying to integrate nexus authentication to jira server. When i tried Nexus Crowd Plugin. Its able to create the external role mapping & user mapping for Crowd group and crowd user.
but not able to login with Crowd user.

I am able to login with Local users, its working fine.
I tried the Crowd test url (nexus/service/local/crowd/test) its returning OK status.

Am I missing any configuration? Please help to fix this issue.

Version Detail ::  Sonatype Nexus :: 2.11.1-01
Nexus Crowd Integration :: 2.9.0
JIRA :: v6.2.7

Thanks in advance,
Kalidas.G

**Comment by flopma** [comment]
Hi, I can't really help as I focus on integration with Crowd server. Have you been able to fix this ?

**Comment by kalganesan** [comment]
Authentication  calls are failing with JIRA Server. In our case,  JIRA authenticate against with our corp Active directory . So I  added Active directory configuration in Nexus and Now nexus Authentication happening with AD and Authorization part happening with JIRA Server. 

Its not a fix, just applied workaround :)

Regards,
Kalidas.G

**Comment by flopma** [comment]
I've tested against jira 6.2.7. The API is the same as Crowd's while it did not work at my side. There were some http 500 errors and stacktraces inside the basic auth filter. Seems to be a problem at Jira side on v6.2.7. Have you tried a more recent version of Jira ?

**Comment by kalganesan** [comment]
I haven't tested against with JIRA latest version. Will try and post you the results.

Regards,
Kalidas.G
