### ISSUE TITLE
Not working on 3.1.0-04

### ISSUE THREAD

**Issue by webmutation** [PatrickRoumanoff/nexus-crowd-plugin#25]
Hi, 

I followed the instructions for a OSS 3.1.0-04 but the plugin (nexus-crowd-plugin-3.0.0.jar) does not even start. I followed the instrcutions on the [wiki ](https://github.com/PatrickRoumanoff/nexus-crowd-plugin/wiki) but no errors. Are there any other necessary steps? Has this been tested on Nexus 3.1 ?

**Comment by flopma** [comment]
Thx for your comment,

It has not been tested under NX 3.1, only NX 3.0 and following your comment, I updated the current wiki page to reflect that fact.

Will release a new version when this is fixed.

**Comment by webmutation** [comment]
Just to let you know also that under 3.1 the proprieties file is looked under /etc/karaf otherwise the plugin will not even start. I was able to install it, however there are still issues like not surviving a server restart. The Karaf config is not being picked up, not sure if this is an issue with the plugin or with Nexus.

**Comment by flopma** [comment]
@webmutation I released version [3.1.0](https://github.com/PatrickRoumanoff/nexus-crowd-plugin/releases/tag/nexus-crowd-plugin-3.1.0) with improved [documentation](https://github.com/PatrickRoumanoff/nexus-crowd-plugin/wiki#setup). The plugin should now be loaded correctly after a restart of Nexus, keeping the realms setup in a stable shape.

Let me know how it goes for you. Thx
