### ISSUE TITLE
Nexus 3 in Docker problem with startup.properties

### ISSUE THREAD

**Issue by ghenadiibatalski** [PatrickRoumanoff/nexus-crowd-plugin#30]
Hello, 

i'm trying to get crowd plugin working with a docker installation of nexus 3. It works just fine until the necessity to modify the startup.properties configuration file. I'm not able to append some values to this file from for example entrypoint.sh because of  missing permissions at this execution stage of the entrypoint.sh. So one have two possibilities:
1. modify this file manually within the running container just like you described in a readme
2. extract the startup.properties from the container, modify it and mount it to the container "hiding" the original one.

The problem with 1. is that after update the modification should be done again. If one forget it, crowd plugin won't be loaded and login failed. The problem with 2. is that after upgrade the startup.properties must be extracted from container, prepared and mounted to container again.

Both ways are not very elegant.  So i would like to know, if there is any possibility to start the plugin without modifying the startup.properties file?

Regards

**Comment by kuhnroyal** [comment]
I am extending the official Docker Image:
```
FROM sonatype/nexus3:3.4.0

ARG CROWD_PLUGIN_VERSION=3.2.2

ENV CROWD_PLUGIN_FOLDER=/opt/sonatype/nexus/system/com/pingunaut/nexus/nexus3-crowd-plugin/${CROWD_PLUGIN_VERSION}

USER root

RUN mkdir -p ${CROWD_PLUGIN_FOLDER} && chown -R nexus:nexus ${CROWD_PLUGIN_FOLDER}
RUN echo "mvn\:com.pingunaut.nexus/nexus3-crowd-plugin/${CROWD_PLUGIN_VERSION} = 200" >> /opt/sonatype/nexus/etc/karaf/startup.properties

USER nexus

ADD conf/crowd/nexus3-crowd-plugin-${CROWD_PLUGIN_VERSION}.jar ${CROWD_PLUGIN_FOLDER}
ADD conf/crowd/nexus3-crowd-plugin-${CROWD_PLUGIN_VERSION}-features.xml ${CROWD_PLUGIN_FOLDER}
ADD conf/crowd/crowd.properties /opt/sonatype/nexus/etc
```

**Comment by ghenadiibatalski** [comment]
I understand, but i would avoid the own image as long as possible...

**Comment by PatrickRoumanoff** [comment]
I think it is awesome the plugin works in docker without changes. well done @kuhnroyal !

**Comment by kuhnroyal** [comment]
@ghenadiibatalski  You might be able to write a custom shell script, mount it and use it as entrypoint. It needs to modify the <code>startup.properties</code> and then call the provided Nexus entrypoint.

**Comment by ghenadiibatalski** [comment]
@kuhnroyal  i've tried this, but the entypoint.sh is not authorized to modify ```startup.properties``` because it runs unter user nexus and ```startup.properties``` is owned by root: in a Dockerfile stands  ```USER nexus```

**Comment by kuhnroyal** [comment]
@ghenadiibatalski Maybe you can change the user with <code>--user root</code> and then switch to nexus in the script.
