### ISSUE TITLE
nexus-crowd-plugin-2.14.0 not able to be activated

### ISSUE THREAD

**Issue by EyckSDLuo** [PatrickRoumanoff/nexus-crowd-plugin#33]
our nexus is Nexus Repository Manager OSS 2.14-2-01
but when I unzip the bundle "nexus-crowd-plugin:2.14.0" to the right place, then restart the nexus, it hits this error
This plugin was not able to be activated

 ... com.roumanoff.nexus:nexus-crowd-plugin:2.14.0 :: action=ACTIVATE result=BROKEN
       Reason: Problem installing: reference:file:/appvol/eFX/data/devtoolsuat/nexus-hk-hosted/plugin-repository/nexus-crowd-plugin-2.14.0/
any ideas?

**Comment by flopma** [comment]
Hi,

The plugin works fine, except for the plugin status page...

Please cd into the folder where nexus-crowd-plugin-2.14.0.jar is and run ls -al * and report back the result please.

Also please report the content of your nexus.properties file.

Regards

**Comment by EyckSDLuo** [comment]
Hi
This issue was fixed. I found the root cause, the bundle needs the nexus version is 2.14.5, after I upgrade our nexus to 2.14.5 from 2.14.2, it works fine. 

Thanks
Eyck

**Comment by EyckSDLuo** [comment]
Hi
I am facing another issue, currently the nexus-crowd-integration plugin is able to activated. and also followed this guideline to enable the OSS Crowd Authentication Realm, I also created a new application in Crowd, I added a external Role Mapping in nexus. but seems the crowd users still can not login nexus directly, I attached the screenshots, could you help on this?

Eyck

**Comment by EyckSDLuo** [comment]
no sure why I cant attach files..

**Comment by eyckluo** [comment]
![capture05](https://user-images.githubusercontent.com/34847707/34812341-38be33da-f69d-11e7-914b-8d393a0f0856.PNG)
![capture07](https://user-images.githubusercontent.com/34847707/34812353-3f0cb040-f69d-11e7-8344-bce84ac30414.PNG)
![capture08](https://user-images.githubusercontent.com/34847707/34812355-3fb669b4-f69d-11e7-812f-29bcd1f94508.PNG)
![capture09](https://user-images.githubusercontent.com/34847707/34812356-4065b00e-f69d-11e7-851f-9a07a7a88525.PNG)
![capture10](https://user-images.githubusercontent.com/34847707/34812358-4134751a-f69d-11e7-84f9-0f7a8eec55f7.PNG)

**Comment by eyckluo** [comment]
![capture10](https://user-images.githubusercontent.com/34847707/34812436-7858d0f4-f69d-11e7-93e2-23ec9a06ace1.PNG)
![capture06](https://user-images.githubusercontent.com/34847707/34812438-7897da74-f69d-11e7-833d-b3398ba12c89.PNG)

**Comment by eyckluo** [comment]
![capture12](https://user-images.githubusercontent.com/34847707/34815764-8dd45d2e-f6aa-11e7-99b7-08788b4ab6cd.PNG)
actually it hang in starting, any idea?

**Comment by eyckluo** [comment]
the issue was fixed, that is because I think the avaiable Realms is the active Realms. but it is not...when I moved the "Oss Crowd Authentication Realm" to "Selected Realms", it works.
Thanks..
