### ISSUE TITLE
Plugin can not sync data automatically when a user group changed

### ISSUE THREAD

**Issue by eyckluo** [PatrickRoumanoff/nexus-crowd-plugin#34]
Hi

May I know if the plugin will cache the role information? below is a sample
Given: 
user 402917 belong to crowd group "nexus-admins"
"nexus admin role" map to "nexus-admins"
delete user 402917 from "nexus-admins"
Result: user 402917 still have "nexus admin role" permission

May I know how to fix this?

Thanks
Eyck

**Comment by flopma** [comment]
Please use the cacheTTL parameter which defaults to 1 hour.

V2 -> https://github.com/PatrickRoumanoff/nexus-crowd-plugin/blob/nexus-2.x/src/main/mdo/crowd-config.xml
V3 -> https://github.com/PatrickRoumanoff/nexus-crowd-plugin/wiki

Regards

**Comment by eyckluo** [comment]
Cool, many thanks flopma!
