### ISSUE TITLE
Version 3.52.0 is compatible with nexus 3.56.0

### ISSUE THREAD

**Issue by gogutza2** [PatrickRoumanoff/nexus-crowd-plugin#38]
Hi,

Could you please tell me if crowd plugin version 3.52.0 is compatible with nexus 3.56.0?

Thank you.

**Comment by PatrickRoumanoff** [comment]
it probably is though you would have to try for yourself.

**Comment by gogutza2** [comment]
I have checked and is working. Thank you!

**Comment by flopma** [comment]
I've uploaded a JAR compiled against 3.56.0 if you prefer... Cheers
