### ISSUE TITLE
external user role mapping login failure

### ISSUE THREAD

**Issue by ststrobel** [PatrickRoumanoff/nexus-crowd-plugin#7]
I'm using the plugin in version 2.0.7.
Crowd is 2.6.4 and Nexus is running 2.6.0-05.

I followed your instructions and am able to do the following:
- look up users
- create external role mapping
- create external user role mapping
- attach roles to users

Using the external role mapping I am able to login and see what is defined in the mapping role. This works perfectly.
However, the external user role mapping doesn't behave correctly. I can create it (it loads the user data from Crowd) and attach roles with privileges to it, but I can't login with that user. Login always tells me a failure. After enabling Debug mode for the logs, following appears:

org.sonatype.sisu.goodies.eventbus.internal.DefaultEventBus - Event 'NexusAuthenticationEvent{userId='bob',remoteIp='X.X.X.X',successful=true}' fired
org.sonatype.nexus.plugins.crowd.client.rest.CachingRestClient - getNestedGroups(bob) from cache
org.sonatype.security.usermanagement.xml.SecurityXmlUserManager - No user role mapping found for user: bob
org.sonatype.sisu.goodies.eventbus.internal.DefaultEventBus - Event 'org.sonatype.nexus.auth.NexusAuthorizationEvent@1ccdcb16' fired
boborg.sonatype.nexus.feeds.record.NexusAuthenticationEventInspector - Successfully authenticated user [bob] from IP address X.X.X.X
org.sonatype.nexus.security.filter.authc.NexusSecureHttpAuthenticationFilter - Request processing is rejected because user "bob" lacks permissions.
org.sonatype.nexus.feeds.record.NexusAuthorizationEventInspector - Unable to authorize user [bob] for read(HTTP method "GET") to /nexus/service/local/authentication/login from IP Address X.X.X.Xuser agent:"n/a"

So Nexus thinks, there is no external user role mapping? But it exists. What do you propose? Thanks

**Comment by vgshine** [comment]
Hi Ststrobel,

Can you please help me get this clarified how the external role mapping works for you in automated way.I am facing issues in my case when I am trying to use "ldap" realm and mapping the external roles to internal nexus roles through an API.

how did you do that?
